-- Generated by HyprMod

-- Environment
hl.env("HYPRCURSOR_THEME", "Volantes-hyprcursor")
hl.env("HYPRCURSOR_SIZE", "24")

-- Settings
hl.config({
    decoration = {
        blur = {
            popups = true,
            size = 5,
        },
    },
    general = {
        allow_tearing = true,
        border_size = 1,
        gaps_in = 3,
        gaps_out = 10,
        layout = "scrolling",
    },
    input = {
        numlock_by_default = true,
    },
    misc = {
        animate_manual_resizes = true,
        animate_mouse_windowdragging = true,
    },
})

-- Bezier curves
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.0}, {0.35, 1.0} } })
hl.curve("skibi", { type = "bezier", points = { {1.0, -0.02}, {0.0, 1.012} } })

-- Animations
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 3.5,
    bezier = "skibi",
})
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 1.0,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 4.4,
    bezier = "easeInOutCubic",
    style = "slidefade",
})

-- Monitors
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "1920x1080@60.03Hz",
    position = "3840x-120",
    scale = 1,
    cm = "srgb",
})

-- Plugins
hl.config({
    plugin = {
        dynamic_cursors = {
            shake = {
                base = 5.0,
                limit = 10.0,
                effects = true,
            },
        },
    },
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpm reload -n")
end)
